
--CANDIDATES
INSERT INTO CANDIDATES (CAN_FNAME, CAN_LNAME) VALUES ('John', 'Romero');
INSERT INTO CANDIDATES (CAN_FNAME, CAN_LNAME) VALUES ('Tom', 'Hall');
INSERT INTO CANDIDATES (CAN_FNAME, CAN_LNAME) VALUES ('Sandy', 'Petersen');
INSERT INTO CANDIDATES (CAN_FNAME, CAN_LNAME) VALUES ('John', 'Carmack');
INSERT INTO CANDIDATES (CAN_FNAME, CAN_LNAME) VALUES ('John', 'Romero');
INSERT INTO CANDIDATES (CAN_FNAME, CAN_LNAME) VALUES ('Dave', 'Taylor');
INSERT INTO CANDIDATES (CAN_FNAME, CAN_LNAME) VALUES ('Adrian', 'Carmack');
INSERT INTO CANDIDATES (CAN_FNAME, CAN_LNAME) VALUES ('Kevin', 'Cloud');
INSERT INTO CANDIDATES (CAN_FNAME, CAN_LNAME) VALUES ('Bobby', 'Prince');

--COMPANIES
INSERT INTO COMPANIES (CMP_NAME) VALUES ('ID software');
INSERT INTO COMPANIES (CMP_NAME) VALUES ('Raven software');
INSERT INTO COMPANIES (CMP_NAME) VALUES ('Activision');
INSERT INTO COMPANIES (CMP_NAME) VALUES ('GT Software');
INSERT INTO COMPANIES (CMP_NAME) VALUES ('Microsoft');
INSERT INTO COMPANIES (CMP_NAME) VALUES ('ION Storm');

--OPENINGS
INSERT INTO OPENINGS (Q_CODE, CMP_CODE, OPEN_START_DATE, OPEN_EST_END_DATE, OPEN_HOURLY_PAY) VALUES ('PRG-C+++', '3', '1998-5-12', '1998-9-12', '15');
INSERT INTO OPENINGS (Q_CODE, CMP_CODE, OPEN_START_DATE, OPEN_EST_END_DATE, OPEN_HOURLY_PAY) VALUES ('PRG-C+++', '6', '1998-5-12', '1999-9-12', '17');
INSERT INTO OPENINGS (Q_CODE, CMP_CODE, OPEN_START_DATE, OPEN_EST_END_DATE, OPEN_HOURLY_PAY) VALUES ('SYS-2', '5', '1999-4-26', '2002-8-7', '40');
INSERT INTO OPENINGS (Q_CODE, CMP_CODE, OPEN_START_DATE, OPEN_EST_END_DATE, OPEN_HOURLY_PAY) VALUES ('SEC-60', '2', '1995-6-26', '1996-2-16', '9');


